version: "3.1"

services:
  global-db:
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres123
      POSTGRESQL_DATABASE: postgres
